name: tube-converter # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2023.3.0-beta3' # just for humans, typically '1.2+git' or '1.3.2'
summary: An easy-to-use YouTube video downloader # 79 char long summary
description: |
 * A basic yt-dlp frontend
 * Supports downloading videos in multiple formats (mp4, webm, mp3, opus, flac, and wav)
 * Run multiple downloads at a time
 * Supports downloading metadata and video subtitles

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
compression: lzo 
architectures:
  - amd64
environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages
package-repositories:
  - type: apt
    components: [kinetic]
    suites: [prebuilt-mpr]
    key-id: B70EAE798718E0FE2972DD0C4FE9F2C43D9428A0
    url: https://proget.makedeb.org
  - type: apt
    components: [main, multiverse, restricted, universe]
    suites: [kinetic, kinetic-backports, kinetic-security, kinetic-updates]
    key-id: F6ECB3762474EDA9D21B7022871920D1991BC93C
    url: http://security.ubuntu.com/ubuntu
parts:
  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-5.1.2.tar.xz
    source-checksum: sha256/619e706d662c8420859832ddc259cd4d4096a48a2ce1eefd052db9e440eef3dc
    autotools-configure-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include
  yt-dlp:
    after: [ffmpeg]
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp.git
    source-tag: 2023.01.06
    python-packages:
      - pyxattr
      - mutagen
      - pycryptodomex
      - websockets
    build-environment:
      # WORKAROUND: The python plugin is broken with gnome extension
      - PATH: ${CRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    override-pull: |
      craftctl default
      sed -i 's/^certifi\\b/#\\0/' requirements.txt
    stage:
      # WORKAROUND: Skip venv from python plugin
      - -bin/activate
      - -bin/activate.csh
      - -bin/activate.fish
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3
      - -bin/python3.10
      - -bin/pip
      - -bin/pip3
      - -bin/pip3.10
      - -pyvenv.cfg
  tube-converter:
    after: 
      - yt-dlp 
      - ffmpeg
    plugin: dump
    source: https://github.com/nlogozzo/NickvisionTubeConverter.git
    source-type: git
    source-tag: ${SNAPCRAFT_PROJECT_VERSION}
    source-subdir: NickvisionTubeConverter.GNOME
    build-packages:
      - brotli
      - blueprint-compiler
      - just
      - rustup
      - dotnet-sdk-7.0
    override-build: |
      cd NickvisionTubeConverter.GNOME
      just publish-self-contained /usr
    override-prime: |
      craftctl default
      cd /root/parts/tube-converter/build/NickvisionTubeConverter.GNOME
      just install /root/prime/
      cd
      sed -e 's|Icon=org.nickvision.tubeconverter|Icon=/usr/share/icons/hicolor/scalable/apps/org.nickvision.tubeconverter.svg|' -i usr/share/applications/org.nickvision.tubeconverter.desktop  
         
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - tube-converter
      - yt-dlp
      - ffmpeg
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gnome-42-2204-sdk
      - core22
    override-prime: |
      set -eux
      for snap in "core22" "gnome-42-2204" "gnome-42-2204-sdk"; do  # List all content-snaps and base snaps you're using here
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
apps:
  tube-converter:
    command: usr/bin/org.nickvision.tubeconverter
    extensions:
      - gnome
    common-id: org.nickvision.tubeconverter
    environment:
      GTK_USE_PORTAL: 1
    desktop: usr/share/applications/org.nickvision.tubeconverter.desktop
    plugs:
      - home
      - network
      - removable-media
